config/routes.rb
Rails.application.routes.draw do
  get 'user_circles/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :circles, only: %i[new create destroy show] do
    resources :user_circles, only: %i[create update]
    resources :circle_events, only: %i[create destroy]
    resources :circle_messages, only: %i[create]
    resources :events, only: %i[new create]
    resources :users, only: :index
    resources :circle_playlists, only: %i[new create destroy]
  end

  resources :events, only: %i[new create destroy edit update show] do
    resources :user_events, only: %i[create update destroy]
    resources :event_messages, only: %i[create]
    resources :circle_events, only: %i[create]
    resources :event_playlists, only: %i[new create destroy]
    resources :payments, only: %i[new create]
  end


  get "profile", to: "users#profile"

  resources :dashboard, only: :show

end

app/views/shared/_circle-show-events.html.erb
    <div class="circle-show-upcoming-events">
      <h2>Upcoming Events</h2>
      <div class="circle-show-upcoming-events-cards">
        <% @circle.events.each do |event| %>
          <%= link_to event_path(event) do %>
            <% if event.photos.attached? %>
          <div class="event-card">
            <div class="title-container">
              <p><%= event.title.upcase %></p>
            </div>
            <div class="image-icon-container" style="background-image: linear-gradient(to bottom, black, black 5%, transparent, transparent 95%), url(<%=cl_image_path event.photos.first.key %>);">
              <div class="icons">
                <div class="attending">
                  <i class="fa-solid fa-user-group"></i>
                  <p><%= event.users.count %></p>
                </div>
                  <% if event.private  %>
                    <i class="fa-solid fa-circle"> </i>
                  <% else %>
                    <i class="fa-regular fa-circle"></i>
                  <% end %>
                  <p><%= event.start_date.strftime("%m/%d") %></p>
              </div>
            </div>
          </div>
              <% else %>
              <div class="event-card">
                <div class="image-icon-container" style="background-image: linear-gradient(rgba(0,0,0,1), rgba(0,0,0,0)), url(<%=cl_image_path "hk6soz418q50zk89hkppwut8mp97" %>)">
                  <div class="icons">
                    <i class="fa-solid fa-user-group"></i>
                  <% if event.private  %>
                    <i class="fa-solid fa-circle"> </i>
                  <% else %>
                    <i class="fa-regular fa-circle"></i>
                  <% end %>
                <p><%= event.start_date.strftime("%m/%d") %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/ch0rizo/Circles"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-logo">
    <%= image_tag "Logo/Circles_Logo.svg", width: "190", class:"white-color" %>
    <p>all rights reserved <i class="fa-regular fa-copyright"></i> 2022</p>
  </div>
</div>

app/views/shared/_home-card.html.erb
<div class="cards-event">
  <% @events.each do |event| %>
    <%= link_to event_path(event) do %>
      <% if event.photos.attached? %>
    <div class="event-card">
      <div class="title-container">
        <p><%= event.title.upcase %></p>
      </div>
      <div class="image-icon-container" style="background-image: linear-gradient(to bottom, black, black 5%, transparent, transparent 95%), url(<%=cl_image_path event.photos.first.key %>);">
        <div class="icons">
          <div class="attending">
            <i class="fa-solid fa-user-group"></i>
            <p><%= event.users.count %></p>
          </div>
            <% if event.private  %>
              <i class="fa-solid fa-circle"> </i>
            <% else %>
              <i class="fa-regular fa-circle"></i>
            <% end %>
            <p><%= event.start_date.strftime("%m/%d") %></p>
        </div>
      </div>
    </div>
        <% else %>
        <div class="event-card">
          <div class="image-icon-container" style="background-image: linear-gradient(rgba(0,0,0,1), rgba(0,0,0,0)), url(<%=cl_image_path "hk6soz418q50zk89hkppwut8mp97" %>)">
            <div class="icons">
                <i class="fa-solid fa-user-group"></i>
              <% if event.private  %>
                <i class="fa-solid fa-circle"> </i>
              <% else %>
                <i class="fa-regular fa-circle"></i>
              <% end %>
            <p><%= event.start_date.strftime("%m/%d") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "New Circle", new_circle_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Event", new_event_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>