config/routes.rb
Rails.application.routes.draw do
  get 'user_circles/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :circles, only: %i[new create destroy show] do
    resources :user_circles, only: %i[create update]
    resources :circle_events, only: %i[create destroy]
    resources :circle_messages, only: %i[create]
    resources :events, only: %i[new create]
    resources :users, only: :index
    resources :circle_playlists, only: %i[new create destroy]
  end

  resources :events, only: %i[new create destroy edit update show] do
    resources :user_events, only: %i[create update destroy]
    resources :event_messages, only: %i[create]
    resources :circle_events, only: %i[create]
    resources :event_playlists, only: %i[new create destroy]
    resources :payments, only: %i[new create]
  end


  get "profile", to: "users#profile"

  resources :dashboard, only: :show

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # reverse_geocoded_by :latitude, :longitude do |obj, geo|
  #   obj.state = geo.state
  #   obj.country_code = geo.country_code
  #   obj.address = [geo.state, geo.country_code].join(",")
  # end
  # after_validation :reverse_geocode

  has_many :user_events
  has_many :users, through: :user_events
  has_many :circle_events
  has_many :circles, through: :circle_events
  has_many :event_messages, dependent: :destroy
  has_many_attached :photos
  has_many_attached :images
  has_many :event_playlists
  has_many :payments, through: :user_events

  validates :title, presence: true
  validates :location, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
    @circles = Circle.all
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.private = params[:event][:private][1]
    if @event.save
      circle = @event.circle_events.first.circle
      UserEvent.create(event: @event, user: current_user)
      circle.users.each do |user|
        user_event = UserEvent.new(event: @event, user: user)
        user_event.save!
      end
      redirect_to event_path(@event), notice: "Event created!"
    else
      redirect_to root_path, notice: "Event not created, please try again"
    end
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def show
    @event = Event.find(params[:id])
    @event_user = current_user
    @user_event = UserEvent.new
    @payment = Payment.new
    @event_message = EventMessage.new
    @circles = @event.circles
    @circle_event = CircleEvent.new
    @event_playlist = EventPlaylist.new
    @marker = Event.where(id: params[:id]).geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
        # info_window: render_to_string(partial: "info_window", locals: {event: event})
      }
    end
  end

  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :location, :private, :user_id, circle_ids: [], photos: [], images: [])
  end
end

app/views/events/_info_window.html.erb
<h4><%=   %></h4>
<%= link_to @event[0].location, "https://www.google.com/maps/@-33.9511852,18.5632344,12z" , class: "btn btn-outline-dark"  %>

app/views/events/new.html.erb
<div class="dashboard-header" data-controller="newevent">
  <%= link_to "<i class='fa-solid fa-arrow-left'></i>".html_safe, :back %>
  <div class="newevent-text"></div>
</div>

<%# Capital cities only! %>
<% city_array = %w[Abu Dhabi Abuja Accra Addis Ababa Algiers Amman Amsterdam Andorra la Vella Ankara
Antananarivo Apia Ashgaba Asmara Astana Asunción Athens Baghdad Baku Bamako Bandar-Seri-Begawan Bangkok
Bangui Banjul Basseterre Beijing Beirut Belgrade Belmopan Berlin Bern Bishkek Bissau Bloemfontein Bogotá
Brasilia Bratislava Brazzaville Bridgetown Brussels Bucharest Budapest Buenos Aires Cairo Canberra
Cape-Town Caracas Castries Chisinau Conakry Copenhagen Dakar Damascus Dhaka Dili Djibouti Dodoma Doha
Dublin Dushanbe Freetown Funafuti Gaborone Georgetown Gitega Guatemala-City Hanoi Harare Havana Helsinki Hamburg
Honiara Islamabad Jakarta Jerusalem Jerusalem (East) Juba Kabul Kampala Kathmandu Khartoum Kigali Kingston
Kingstown Kinshasa Kuala Lumpur Kuwait City Kyiv (also known as Kiev) La Paz  Libreville Lilongwe Lima
Lisbon Ljubljana Lobamba Lomé London Luanda Lusaka Luxembourg  Madrid Majuro Malabo Male Managua Manama
Manila Maputo Maseru Mbabane Mexico City Minsk Mogadishu Monaco Monrovia Montevideo Moroni Moscow Muscat
Nairobi Nassau Naypyidaw N'Djamena New Delhi Ngerulmud Niamey Nicosia Nouakchott Nukuʻalofa Oslo Ottawa
Ouagadougou Oyala Palikir Panama-City Paramaribo Paris Phnom-Penh Podgorica Port-Louis Port-Moresby
Port-of-Spain Port-Vila Port-au-Prince Porto-Novo Prague Praia Pretoria Pristina Pyongyang Quito Rabat
Reykjavik Riga Riyadh Rome Roseau Saint George's Saint-John's San-Jose San-Marino San-Salvador Sana'a
Santiago Santo Domingo São Tomé Sarajevo Seoul Singapore Skopje Sofia Sri Jayawardenepura Kotte Stockholm
Sucre  Suva Taipei Tallinn Tarawa Tashkent Tbilisi Tegucigalpa Tehran Thimphu Tirana Tokyo Tripoli Tunis
Ulaanbaatar Vaduz Valletta Vatican City Victoria Vienna Vientiane Vilnius Warsaw Washington-D.C. Wellington
Windhoek Yamoussoukro Yaounde Yaren District Yerevan Zagreb] %>

<div class="container-form">
  <h2>CREATE A NEW EVENT</h2>
  <%= simple_form_for @event do |f| %>
    <%= f.input :title %>
    <%= f.input :location, collection: city_array , input_html: {data: {controller: 'tom-select'}}  %>
    <%= f.input :private, as: :radio_buttons, collection: [['Yes',true], ['No',false]], required: true %>
    <%= f.input :photos, as: :file , input_html: { multiple: true } %>
    <%= f.input :start_date, as: :string, input_html: {data: { controller: "flatpicker"}} %>
    <%= f.input :end_date, as: :string, input_html: {data: { controller: "flatpicker"}} %>
    <%= f.association :circles, collection: current_user.circles.each {|circle| circle.name}, input_html: { class: 'multiselectuser'} %>
    <%= f.submit %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event-header" data-controller="attend" data-attend-url-value="<%= event_user_events_url(@event) %>">
  <div class="event-header-left">
    <h1><%= link_to "<i class='fa-solid fa-arrow-left'></i>".html_safe, root_path %></h1>
  </div>
  <div class="event-header-middle">
    <div class="event-header-middle-title">
      <h2><%= @event.title.upcase %></h2>
    </div>
    <div class="event-header-middle-info">
      <p>
        <i class="fa-solid fa-user-group"></i>
        <span data-attend-target="userCount"><%= @event.users.count %></span>
        <% if @event.private? %>
          <i class="fa-solid fa-lock"></i> Private
        <% else %>
          <i class="fa-solid fa-unlock"></i> Public
        <% end %>
      </p>
      <p><%= @event.start_date.strftime("%a, %b %d") %> - <%= @event.end_date.strftime("%a, %b %d") %></p>
    </div>
  </div>
  <div class="event-header-right">
    <div class="event-header-right-attending">
      <%= link_to "Attend Event", event_user_events_path(@event), data: { turbo_method: :post, action: "click->attend#clicky" }, class:"btn btn-success loool" %>
    </div>
  </div>
</div>
<div class="event-main-container">
  <div class="event-left-side-container">
    <div class="event-left-side-banner">
      <div class="event-show-carousel-container">
        <div class="event-show-carousel-slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% @event.photos.each_with_index do |photo, index| %>
              <% if index == 0 %>
                <div class="carousel-item active">
                  <%= cl_image_tag photo.key, class: "d-block w-100 event-photo"%>
                </div>
                  <% else %>
                <div class="carousel-item">
                  <%= cl_image_tag photo.key, class: "d-block w-100 event-photo"%>
                </div>
                  <% end %>
              <% end %>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselPhotosControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselPhotosControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
          </div>
        </div>
      </div>
    </div>
    <div class="event-left-side-bottom">
      <div class="event-show-chatroom-container">
        <div class="event-show-chatroom-header">
          <h5><%= @event.title.upcase %> CHAT</h5>
        </div>
          <div class="event-show-chatroom" data-controller="event-chatroom-subscription" data-event-chatroom-subscription-chatroom-id-value="<%= @event.id %>" data-event-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

          <div class="messages" data-event-chatroom-subscription-target="messages">
            <% @event.event_messages.each do |event_message| %>
              <div class="message-row d-flex <%= event_message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
                <div class="<%= event_message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                  <%= render "event_messages/event_message", event_message: event_message %>
                </div>
              </div>
            <% end %>
          </div>
          <%= simple_form_for [@event, @event_message], html: { data: { action: "turbo:submit-end->event-chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
          <%= f.input :content, label: false, placeholder: "Message #{@event.title}", wrapper_html: {class: "flex-grow-1"} %>
          <%= f.submit "Send", class: "global-button-chat" %>
          <% end %>
        </div>
      </div>
      <div class="event-right-side-music">
      <div class="spotify-playlists-header">
        <h5>EVENT PLAYLISTS</h5>
        <!-- Playlist Button trigger modal -->
        <button type="button" class="global-button" id="playlist-button", data-bs-toggle="modal" data-bs-target="#addPlaylist">
          <h5>+</h5>
        </button>
      </div>
      <div class="event-playlists-grid">
        <% @event.event_playlists.each do |playlist| %>
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/<%=playlist.embed_url%>?utm_source=generator&theme=0" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        <% end %>
      </div>

        <!-- Modal -->
        <div class="modal fade" id="addPlaylist" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="AddPlaylistLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content modal-content-circle-show">
              <div class="modal-header">
                <i class="fa-brands fa-spotify"></i>
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add a Playlist</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body modal-body-content">
                <%= simple_form_for [@event, @event_playlist] do |f| %>
                  <%= f.input :url, label: 'Enter the link to your playlist' %>
                  <%= f.submit "Add" %>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="event-left-side-anker">
      <div class="anker-splitty">
        <div class="splitty">
          <h5>SPLITTY - EVENT COSTS</h5>
          <div class="splitty-body">
            <div class="splitty-people">
              <% @event.user_events.sort_by {|user| user.balance * user.balance }.reverse.each do |user_event| %>
                <p><%= user_event.user.first_name %>: R <%= user_event.balance %></p>
              <% end %>
            </div>
            <%= simple_form_for [@event, @payment] do |f| %>
              <%= f.input :amount %>
              <%= f.input :description %>
              <%= f.association :user_event, label: "Payer", collection: @event.user_events, label_method: :user_name, required: false %>
              <p>Who's splittin' this?</p>
              <div class="potential-splitters mb-3">
                <%= f.association :user_events, as: :check_boxes, collection: @event.user_events, label: "", label_method: :user_name %>
              </div>
              <%= f.submit "Pop it on the Splitty!", class: "global-button-splitty" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="event-right-side-location">
        <h5><i class="fa-solid fa-location-dot"></i> LOCATION : <%= @event.location %></h5>
        <div class="event-right-side-location-body">
          <div class="event-right-side-location-body-address d-flex"></div>
        </div>
        <div class="event-right-side-map">
          <div class="event-show-details-info-location">
            <div class="event-show-details-info-location-map"
              data-controller="map"
              data-map-markers-value="<%= @marker.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="event-right-side-container">
    <div class="event-right-side-host">
      <h5>HOSTED BY</h5>
      <div class="event-right-side-host-card">
        <%= link_to dashboard_path(@event.user_id) do %>
          <div class="event-right-side-host-body">
            <%= cl_image_tag User.find(@event.user_id).photo.key %>
            <div class="event-right-side-host-info">
              <h4><%= User.find(@event.user_id).first_name %> <%= User.find(@event.user_id).last_name %></h4>
              <p>Joined <%= User.all.first.created_at.strftime("%b %Y") %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="event-right-side-invite">
      <h5>INVITE A CIRCLE</h5>
      <div class="circle-grid">
        <% @circles.each do |circle|%>
          <%= link_to circle_path(circle) do %>
            <% if circle.photo.key? %>
              <%= cl_image_tag circle.photo.key, class: "circle-avatar", :style => "border-color: #{circle.border_color}", alt: "Circle Avatar" %>
            <% else %>
              <%= cl_image_tag "hk6soz418q50zk89hkppwut8mp97", class: "circle-avatar", alt: "circle-avatar" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <%= simple_form_for [@event, @circle_event] do |f| %>
        <div class="event-right-side-invite-body">
          <div class="event-right-side-invite-body-circles">
            <%= f.association :circle, as: :radio_buttons, required: false, label: "", collection: current_user.circles %>
          </div>
        </div>
        <%= f.button :submit, "Add Circle", class:"event-add-circle-button" %>
      <% end %>
    </div>
      <div class="event-right-side-details">
        <div class="event-right-side-details-header">
          <h5>DETAILS</h5>
        </div>
        <div class="event-right-side-details-body">
          <div class="event-right-side-details-date d-flex">
            <p><i class="fa-solid fa-calendar-days"></i></p>
            <p><strong>START:</strong> <%= @event.start_date.strftime("%A, %B %d, %Y") %> <br> <strong>END:</strong> <%= @event.end_date.strftime("%A, %B %d, %Y") %></p>
          </div>
          <div class="event-right-side-details-private d-flex">
            <% if @event.private? %>
              <p><i class="fa-solid fa-lock"></i></p>
              <p>Private Event</p>
            <% else %>
              <p><i class="fa-solid fa-unlock"></i></i></p>
              <p>Public Event</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="anker-member">
        <h5>ATTENDEES</h5>
        <div class="anker-member-info">
          <ul>
            <% @event.users.each do |user| %>
              <li><%= cl_image_tag user.photo.key %>
                  <p><%= user.first_name %> <%= user.last_name %></p>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>