config/routes.rb
Rails.application.routes.draw do
  get 'user_circles/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :circles, only: %i[new create destroy show] do
    resources :user_circles, only: %i[create update]
    resources :circle_events, only: %i[create destroy]
    resources :circle_messages, only: %i[create]
    resources :events, only: %i[new create]
    resources :users, only: :index
    resources :circle_playlists, only: %i[new create destroy]
  end

  resources :events, only: %i[new create destroy edit update show] do
    resources :user_events, only: %i[create update destroy]
    resources :event_messages, only: %i[create]
    resources :circle_events, only: %i[create]
    resources :event_playlists, only: %i[new create destroy]
    resources :payments, only: %i[new create]
  end


  get "profile", to: "users#profile"

  resources :dashboard, only: :show

end

app/models/circle.rb
class Circle < ApplicationRecord
  has_many :circle_events
  has_many :events, through: :circle_events
  has_many :user_circles
  has_many :users, through: :user_circles
  has_many :circle_messages, dependent: :destroy
  has_one_attached :photo
  has_one_attached :banner
  has_many :circle_playlists

  validates :name, presence: true
  validates :photo, presence: true
  validates :banner, presence: true
  validates :border_color, presence: true
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  def new
    @circle = Circle.new
    @users = current_user.friends
    @user_names = @users.pluck(:first_name)
    @colors = %w[#33a8c7 #52e3e1 #a0e426 #fdf148 #ffab00 #f77976 #f050ae #d883ff #9336fd #ffbe0b #fb5607 #ff006e #8338ec #3a86ff]
  end

  def create
    @circle = Circle.new(circle_params)
    if @circle.save
      @circle.users << current_user
      # params[:circle]["user_ids"].each do |friend|
      #   @circle.users << User.find_by(first_name: friend) if friend != ""
      # end
      redirect_to @circle, notice: 'New Circle created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @users = User.all
    @circle = Circle.find(params[:id])
    @circle_events = CircleEvent.where(@circle_id)
    @circle_message = CircleMessage.new
    @user_circle = UserCircle.new
    @not_in_group_users = User.where.not(id: @circle.users.map(&:id))
    @other_users = @circle.users.reject { |user| user == current_user }
    @circle_playlist = CirclePlaylist.new
  end

  def destroy
    @circle = Circle.find(params[:id])
    if current_user == @circle.user
      @circle.destroy
    end

    redirect_to root_path
  end

  private

  def circle_params
    params.require(:circle).permit(:name, :photo, :private, :border_color, :banner, user_ids: [])
  end
end

app/views/circles/_users_list.html.erb
<div data-search-users-target="users_list">
  <div class="users">
    <% users.each do |user| %>
      <div class="circle-add-friend"
        data-controller="friend"
        data-friend-user-id-value="<%= user.id %>"
        data-friend-circle-id-value="<%= circle.id %>"
      >
        <div class="circle-img-add-friend">
          <%= cl_image_tag user.photo.key %>
        </div>
        <div class="circle-add-friend-info">
          <p><%= user.full_name %></p>
          <p><%= button_tag "Add", class: "button-adding-friends", data: { action: "friend#submit", "friend-target" => "button" } %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/circles/new.html.erb
<div class="container-form">
  <h2>CREATE A NEW CIRCLE</h2>
  <%= simple_form_for @circle do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.input :private, as: :radio_buttons, collection: [['Yes',true], ['No',false]], required: true %>
    <%= f.input :banner, as: :file %>
    <%= f.input :border_color, as: :radio_buttons, collection_wrapper_tag: "div", collection_wrapper_class: "color-select-wrapper",
                label: "Choose a color for your circle" , collection: @colors, item_wrapper_class: "circle-color-input",
                input_html: { class: 'multiselectuser', value: ""}%>
    <% if @user_names.length <= 0 %>
      <%= "You have no friends to invite" %>
    <% else %>
      <%= f.association :users, label: "Who do you want to add to your circle?" , collection: User.all, label_method: :full_name, input_html: { class: 'multiselectuser'}%>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>

app/views/circles/show.html.erb
<% if @circle.banner.key? %>
  <div class="circle-show-banner">
    <%= cl_image_tag @circle.banner.key %>
    <%= link_to "<i class='fa-solid fa-arrow-left'></i>".html_safe, root_path %>
  </div>
<% else %>
  <div class="circle-show-banner">
    <%= cl_image_tag "0x0_bfxmqe" %>
    <%= link_to "<i class='fa-solid fa-arrow-left'></i>".html_safe, root_path %>
  </div>
<% end %>
<div class="circle-show-title">
  <%= cl_image_tag @circle.photo.key, class: "circle-avatar-circle", :style => "border-color: #{@circle.border_color}", alt: "circle-avatar" %>
  <div class="circle-show-details">
    <h1><%= @circle.name.upcase %></h1>
    <p class="mb-2"><%= @circle.created_at.strftime("STARTED %b %Y") %></p>
    <div class="circle-show-details-private">
      <p><i class="fa-solid fa-user-group"></i><%= @circle.users.count %> MEMBERS</p>
      <% if @circle.private == true %>
        <p><i class="fa-solid fa-circle"></i>PRIVATE</p>
      <% else %>
        <p><i class="fa-regular fa-circle"></i>OPEN</p>
      <% end %>
    </div>
    <!-- Button trigger modal -->
    <button type="button" class="btn global-button-circle-show" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
      <i class="fa-solid fa-plus"></i>
      <i class="fa-solid fa-user-group"></i>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content modal-content-circle-show">
          <div class="modal-header">
            <i class="fa-regular fa-address-book"></i>
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Add friends</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body modal-body-content">
            <div data-controller="search-users">
                <%= form_with url: circle_users_path(@circle), method: :get, html: {class: "mb-4", data: {search_users_target: "form"}} do |f| %>
                  <%= f.text_field :query,
                                   class: "form-control",
                                   placeholder: "Type a user name",
                                   value: params[:query],
                                   data: {
                                    search_users_target: "input",
                                    action: "keyup->search-users#update"
                                   }
                                   %>
                <% end %>
                <%= render "users_list", users: @not_in_group_users, circle: @circle %>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to "Done!", circle_path(@circle) %>
          </div>
        </div>
      </div>
    </div>
    <div class="btn global-button-circle-show">
      <%= link_to "Create Event", new_event_path  %>
    </div>
  </div>
</div>

<div class="circle-show-main-container">
  <div class="circle-show-main-left">
    <div class="circle-show-main-top">

      <div class="circle-show-members-container">
        <div class="circle-show-members-header">
          <h5>MEMBERS</h5>
        </div>
        <div class="circle-show-members-info">
        <div>
        </div>
          <ul style="list-style: none">
            <% @circle.users.each do |user| %>
            <li style="font-size: 12px"><%= cl_image_tag user.photo.key %> <%= user.first_name.upcase %> <%= user.last_name.upcase %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="circle-show-upcoming-events-container">
        <div class="circle-show-upcoming-events-header">
          <h5>UPCOMING EVENTS</h5>
        </div>
        <div class="circle-show-upcoming-events-cards">
          <% if @circle.events.length != 0 %>
            <% @circle.events.each do |event| %>
              <% if event.start_date.future? %>
                <%= link_to event_path(event) do %>
                  <% if event.photos.attached? %>
                    <div class="circle-show-event-card">
                      <div class="title-container">
                        <p><%= event.title.upcase %></p>
                      </div>
                      <div class="image-icon-container" style="background-image: linear-gradient(to bottom, black, black 5%, transparent, transparent 95%), url(<%=cl_image_path event.photos.first.key %>);">
                        <div class="icons">
                          <div class="attending">
                            <i class="fa-solid fa-user-group"></i>
                            <p><%= event.users.count %></p>
                          </div>
                          <% if event.private  %>
                            <i class="fa-solid fa-circle"> </i>
                          <% else %>
                            <i class="fa-regular fa-circle"></i>
                          <% end %>
                          <p><%= event.start_date.strftime("%m/%d") %></p>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <div class="circle-show-event-card">
                      <div class="image-icon-container" style="background-image: linear-gradient(rgba(0,0,0,1), rgba(0,0,0,0)), url(<%=cl_image_path "hk6soz418q50zk89hkppwut8mp97" %>)">
                        <div class="icons">
                            <i class="fa-solid fa-user-group"></i>
                          <% if event.private  %>
                            <i class="fa-solid fa-circle"> </i>
                          <% else %>
                            <i class="fa-regular fa-circle"></i>
                          <% end %>
                          <p><%= event.start_date.strftime("%m/%d") %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% else %>
          <p>You have no upcoming events...</p>
          <% end %>
          </div>
        </div>

    </div>
    <div class="circle-show-main-bottom">
      <div class="circle-show-memories-container">
        <div class="circle-show-memories-header">
          <h5>MEMORIES</h5>
        </div>
        <div class="circle-show-memories-slider-container">
          <section class="splide my-3" aria-label="Splide Basic HTML Example" data-controller="slider">
            <div class="splide__track">
              <ul class="splide__list">
                <% @circle.events.each do |event| %>
                  <li class="splide__slide"><%= cl_image_tag event.photos[0].key %></li>
                <% end %>
              </ul>
            </div>
          </section>
        </div>
      </div>
      <div class="circle-show-spotify-playlists">
        <div class="spotify-playlists-header">
          <h5>CIRCLE PLAYLISTS</h5>
          <!-- Playlist Button trigger modal -->
          <button type="button" class="global-button" id="playlist-button", data-bs-toggle="modal" data-bs-target="#addPlaylist">
            <h5>+</h5>
          </button>
        </div>
        <div class="playlists-grid">
          <% @circle.circle_playlists.each do |playlist| %>
            <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/<%=playlist.embed_url%>?utm_source=generator&theme=0" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
          <% end %>
        </div>

          <!-- Modal -->
          <div class="modal fade" id="addPlaylist" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="AddPlaylistLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
              <div class="modal-content modal-content-circle-show">
                <div class="modal-header">
                  <i class="fa-brands fa-spotify"></i>
                  <h1 class="modal-title fs-5" id="staticBackdropLabel">Add a Playlist</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body modal-body-content">
                  <%= simple_form_for [@circle, @circle_playlist] do |f| %>
                    <%= f.input :url, label: 'Enter the link to your playlist' %>
                    <%= f.submit "Add" %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="circle-show-main-right">
    <div class="circle-show-chatroom-container">
      <div class="circle-show-chatroom-header">
        <h5><%= @circle.name.upcase %> CHAT</h5>
      </div>
        <div class="circle-show-chatroom" data-controller="circle-chatroom-subscription" data-circle-chatroom-subscription-chatroom-id-value="<%= @circle.id %>" data-circle-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

        <div class="messages" data-circle-chatroom-subscription-target="messages">
          <% @circle.circle_messages.each do |circle_message| %>
            <div class="message-row d-flex <%= circle_message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
              <div class="<%= circle_message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                <%= render "circle_messages/circle_message", circle_message: circle_message %>
              </div>
            </div>
          <% end %>
        </div>
        <%= simple_form_for [@circle, @circle_message], html: { data: { action: "turbo:submit-end->circle-chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
        <%= f.input :content, label: false, placeholder: "Message #{@circle.name}", wrapper_html: {class: "flex-grow-1"} %>
        <%= f.submit "Send", class: "global-button-chat mb-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>